[build]
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/test"
  to = "/.netlify/functions/test"
  status = 200
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/api/apollo/*"
  to = "/.netlify/functions/apollo-proxy"
  status = 200
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 