[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/test-api"
  status = 200

[[redirects]]
  from = "/api/apollo/*"
  to = "/.netlify/functions/apollo-proxy"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200