[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/apollo/*"
  to = "/.netlify/functions/apollo-proxy"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200